### ISSUE TITLE
Cosmoing checklist

### ISSUE THREAD

**Issue by mikemerin** [mikemerin/FM2020-layouts#6]
- [x] Piece Extravaganza + Bonus: pieceofcheese87, 608, 1:00:00, Event, Quiz Show, 1P layout
- [x] Coinflip Tournament: cosmoing, 16:9, 0:45:00, Event, N/A, 1P layout
- [x] The -> "Mystery" Finale Game: wolsk, 600, 0:05:00, Solo Run, Meme or N/A, 1P layout
- [ ] Relay Race: same as last year but maybe better and fresher. Order is Yellow Star -> Micromedley -> Bread -> Novelty
- [x] Blind Sudoku: arzztt + cosmoing + riktoi + Andres_tearit, 608, 1:30:00, Event, Meme, 4P layout
- [x] Blind Needle: Yiazmat7 + TheNewGeezer + Tehninza + sunbla, 608, 1:45:00, Event, Needle + Gimmick, 4P layout
- [x] Blind Adventure: wolsk + Wolfiexe + Gaborro + Fragnaticc, 608, 2:00:00, Event, Gimmick + Medley + Needle (check with Naloas), 4P layout
- [ ] Avoidance Tournament: names will have to change as we go, 600, 2:30:00, Event, Avoidance, 2P layout
- [ ] Blind IWM: names will have to change as we go, 608, 1:00:00, Event, N/A, 2P layout
- [ ] Fish out of water: bummerman222 (megaman) + Cheez (sm64) + The Reverser of Time (fangaem), 8:7 + 10:7 + 608, 1:30:00, Event, N/A, 3P layout

- [ ] maybe change meme to sudoku, or add sudoku genre and everything in sudoku block should have sudoku/meme
- [ ] remove Subfusc_moose from Destination, commentators should be cosmoing + wolsk
- [ ] Densha de D: Lightning Stage commentator is Lordmau5
- [ ] Designer L's Wacky Randventure WR is now 19:01 by Tehninza
- [ ] Fangame Music DJ Set genre should be Music, run type should be Showcase
- [ ] Gensou Skydrift genres should not include Adventure
- [ ] Ghost Mechanism run type should be Showcase
- [ ] Gm8Emulator is kinda broken for run info? run type should be TAS Showcase
- [ ] I wanna be the guy should not have Gimmick genre, WR/PB should be 27:51
- [ ] I wanna be the justice should have Avoidance and Needle genres, Twitch Handle should be ヒョウカ (hyo_ka)
- [ ] I wanna be the salt should have Avoidance and Trap genres, Twitch Handle should be ヒョウカ (hyo_ka)
- [ ] I wanna be the with friends WR/PB should be 11:21
- [ ] get the Kill the Guy record (it's 34:10 by letcreate123)
- [ ] I wanna make a sandwich should have the Trap genre
- [ ] I wanna see the moon should have Gimmick genre, should not have Needle genre
- [ ] Mario Party 64 WR should be 32:07 by Cavin856
- [ ] Metroid Fusion: Oil Spill WR/PB should be talk to hercules but i'm sure wolsk is gonna do that
- [ ] Nimpize Adventure commentator is Benjee
- [ ] NitorInc run type should be Showcase
- [ ] Sonic Chrono Adventure should not have adventure genre
- [ ] Star Revenge 2.5: Remnant of Doom WR is 1:11:28 by InfiniteVoid316
- [ ] Sunlust WR holder is missing/wrong
- [ ] Super Mario 74 Extreme Edition WR is 30:15 by CartoonBuffoon
- [ ] Touhou Danmakufu run type should be showcase
- [ ] Super Metroid Y-Faster 2 Fast PB/WR should be 58:44
- [ ] 美鈴とチルノの妖怪の山大冒険 has some loading issues?
